"""initial

Revision ID: 2c25148d0fb7
Revises: 
Create Date: 2026-07-12 01:20:31.598458

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c25148d0fb7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_sha256', name='uq_books_sha256')
    )
    op.create_index('idx_books_created', 'books', ['created_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'book_id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('spine_order', sa.Integer(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'book_id')
    )
    op.create_index('idx_chapters_book', 'chapters', ['book_id', 'spine_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chapters_book', table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('assets')
    op.drop_index('idx_books_created', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
