"""initial

Revision ID: 2c25148d0fb7
Revises:
Create Date: 2026-07-12 01:20:31.598458

这是 Alembic 自动生成的初始迁移脚本。
Alembic "迁移"相当于数据库的"版本控制"——每次数据库结构变化（加表、加列、改索引等）
都会生成一个这样的脚本文件。upgrade() 是"前进"，downgrade() 是"回退"。
"""
from collections.abc import Sequence  # 泛型序列类型

import sqlalchemy as sa  # 通常用 sa 作为 SQLAlchemy 的缩写
from alembic import op  # op 是 Alembic 的操作对象，提供 create_table / drop_index 等方法

# revision identifiers, used by Alembic.
# Alembic 用这些标识追踪迁移历史链：
#   - revision：这个迁移的唯一 ID（git commit hash 风格）
#   - down_revision：这个迁移的"父"（回退到哪个版本）。None 表示它是第一个迁移
#   - branch_labels / depends_on：多分支迁移时用，这里都是 None 表示线性历史
revision: str = '2c25148d0fb7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    执行"升级"操作：创建三张表（books, assets, chapters）及索引和约束。
    op.create_table() 会生成 CREATE TABLE SQL 语句。
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建 books 表——对应 ORM 中的 Book 模型
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),           # 主键，UUID 格式
    sa.Column('title', sa.Text(), nullable=False),                   # 书名
    sa.Column('authors', sa.JSON(), nullable=False),                 # 作者列表（JSON 数组）
    sa.Column('language', sa.String(length=16), nullable=False),     # 语言代码
    sa.Column('publisher', sa.Text(), nullable=True),                # 出版社（可为空）
    sa.Column('description', sa.Text(), nullable=True),              # 简介（可为空）
    sa.Column('pub_date', sa.Date(), nullable=True),                 # 出版日期（可为空）
    sa.Column('identifier', sa.Text(), nullable=False),              # ISBN 或其他标识
    sa.Column('file_path', sa.Text(), nullable=False),               # 磁盘文件路径
    sa.Column('file_size', sa.Integer(), nullable=False),            # 文件大小
    sa.Column('file_sha256', sa.String(length=64), nullable=False),  # 文件哈希（查重用）
    sa.Column('created_at', sa.DateTime(), nullable=False),          # 入库时间
    sa.PrimaryKeyConstraint('id'),                                   # 主键约束
    sa.UniqueConstraint('file_sha256', name='uq_books_sha256')       # 哈希唯一约束（防止重复导入）
    )
    op.create_index('idx_books_created', 'books', ['created_at'], unique=False)

    # 创建 assets 表——存储 EPUB 中的资源文件（图片、CSS 等）
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Integer(), nullable=False),            # 0 或 1，标记是否是封面
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),  # 外键，级联删除
    sa.PrimaryKeyConstraint('id', 'book_id')                                # 复合主键
    )

    # 创建 chapters 表——存储 EPUB 中的章节
    op.create_table('chapters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('spine_order', sa.Integer(), nullable=False),          # 章节在 spine 中的顺序
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),                    # 纯文本（搜索/字数用）
    sa.Column('html', sa.Text(), nullable=False),                    # 原始 HTML（渲染用）
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'book_id')
    )
    op.create_index('idx_chapters_book', 'chapters', ['book_id', 'spine_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """downgrade schema.

    Upgrade 的反操作——"回退"：按依赖顺序逆序删表。
    必须先删子表（chapters, assets），再删主表（books），
    因为子表有外键引用主表。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chapters_book', table_name='chapters')  # 先删索引
    op.drop_table('chapters')                                  # 再删章节表
    op.drop_table('assets')                                    # 删资源表
    op.drop_index('idx_books_created', table_name='books')
    op.drop_table('books')                                     # 最后删书表
    # ### end Alembic commands ###
